"""
WorkspaceToolBase
=================
Boilerplate base class for Maya 2022+ dockable/floating tools.
Compatible with Maya 2022-2024 (PySide2) and Maya 2025+ (PySide6).

SETUP (userSetup.py)
--------------------
    import sys
    sys.path.insert(0, r"/path/to/parent/of/my_tools")

CREATING A NEW TOOL
-------------------
    1. Copy example_tool.py and rename the class.
    2. Set TOOL_NAME (unique, no spaces) and TOOL_TITLE.
    3. Implement build_ui(self) to populate self.main_layout.
    4. Call YourTool.show() to open it.

STARTUP RESTORE
---------------
    If Maya closes with the panel open, it will reopen automatically on
    next launch — provided your package is on sys.path in userSetup.py.

DO NOT EDIT THIS FILE.
"""

import maya.cmds as cmds
import maya.OpenMayaUI as omui
from maya.api import OpenMaya as om

try:
    from PySide2 import QtWidgets, QtCore
    from shiboken2 import wrapInstance
except ImportError:
    from PySide6 import QtWidgets, QtCore
    from shiboken6 import wrapInstance


def _maya_main_window():
    """Return Maya's main window as a QMainWindow."""
    ptr = omui.MQtUtil.mainWindow()
    return wrapInstance(int(ptr), QtWidgets.QMainWindow)


class WorkspaceToolBase(QtWidgets.QWidget):
    """
    Subclass this. Override TOOL_NAME, TOOL_TITLE, and build_ui().

    Open your tool with:
        YourSubclass.show()
    """

    TOOL_NAME      = "WorkspaceToolBase"  # Unique ID — no spaces, no special chars
    TOOL_TITLE     = "Tool"               # Displayed in the panel header
    DEFAULT_WIDTH  = 300
    DEFAULT_HEIGHT = 400

    def __init__(self, parent=None):
        super().__init__(parent)
        self.main_layout = QtWidgets.QVBoxLayout(self)
        self.main_layout.setContentsMargins(4, 4, 4, 4)
        self.build_ui()

    def build_ui(self):
        """
        Override in subclass.
        Add your widgets to self.main_layout here.
        """
        pass

    # ── Public API ───────────────────────────────────────────────────────────

    @classmethod
    def show(cls):
        """
        Open the panel.
        - If already open: raises it to the top.
        - If closed: creates it, restoring last position/dock state.
        - First launch: opens floating, centered on Maya's main window.
        """
        if cmds.workspaceControl(cls.TOOL_NAME, exists=True):
            # "raise" is a Python keyword so it can't be passed as a kwarg directly.
            # Passing it via **{} dict unpacking sidesteps the parser.
            cmds.workspaceControl(cls.TOOL_NAME, edit=True, **{"raise": True}, visible=True)
            return
        cls._create()

    @classmethod
    def rebuild(cls):
        """
        Called automatically by Maya's uiScript on workspace restore at startup.
        Do not call this manually.
        """
        name = cls.TOOL_NAME
        if not cmds.workspaceControl(name, exists=True):
            return
        cls._populate_control(name)

    @classmethod
    def _on_close(cls):
        """
        Called by the workspaceControl's closeCommand just before destruction.
        Saves position and dock state so the next open can restore them.
        """
        cls._save_state()

    @classmethod
    def clear_saved_state(cls):
        """
        Remove all saved optionVars for this tool.
        Next open will use defaults (floating, centered on Maya).
        Useful for debugging or resetting a tool's layout.
        """
        for key in ("floating", "x", "y", "width", "height", "dockArea"):
            var = cls._opt(key)
            if cmds.optionVar(exists=var):
                cmds.optionVar(remove=var)
        om.MGlobal.displayInfo(f"[{cls.TOOL_NAME}] Saved state cleared.")

    # ── Private ──────────────────────────────────────────────────────────────

    @classmethod
    def _opt(cls, key):
        """Namespaced optionVar key for this tool."""
        return f"{cls.TOOL_NAME}_{key}"

    @classmethod
    def _ui_script(cls):
        """
        Python string Maya re-executes to rebuild the panel on startup.
        Auto-generated from the subclass's own module path — no manual
        string editing needed when you copy the file.
        """
        return (
            f"import {cls.__module__}; "
            f"{cls.__module__}.{cls.__name__}.rebuild()"
        )

    @classmethod
    def _close_command(cls):
        """
        Python string executed by Maya when the user closes the panel.
        closeCommand expects a raw Python string, not MEL.
        Calls back into Python to save state before the control is destroyed.
        """
        return (
            f"import {cls.__module__}; "
            f"{cls.__module__}.{cls.__name__}._on_close()"
        )

    # ── State persistence ────────────────────────────────────────────────────

    @classmethod
    def _load_state(cls):
        """
        Read saved optionVars.
        Returns a dict of state values, or None if this tool has never been opened.
        """
        if not cmds.optionVar(exists=cls._opt("floating")):
            return None

        state = {
            "floating": bool(cmds.optionVar(q=cls._opt("floating"))),
            "x":        cmds.optionVar(q=cls._opt("x")),
            "y":        cmds.optionVar(q=cls._opt("y")),
            "width":    cmds.optionVar(q=cls._opt("width")),
            "height":   cmds.optionVar(q=cls._opt("height")),
        }

        # dockArea is only saved when docked; fall back to right
        dock_key = cls._opt("dockArea")
        state["dock_area"] = (
            cmds.optionVar(q=dock_key)
            if cmds.optionVar(exists=dock_key)
            else "right"
        )

        return state

    @classmethod
    def _save_state(cls):
        """
        Read the current panel position/dock state and write to optionVars.
        Called by _on_close() before the control is destroyed.
        """
        name = cls.TOOL_NAME
        if not cmds.workspaceControl(name, exists=True):
            return

        is_floating = cmds.workspaceControl(name, q=True, floating=True)
        cmds.optionVar(iv=(cls._opt("floating"), int(is_floating)))

        # Get position and size via Qt — cmds doesn't expose coordinates
        ptr = omui.MQtUtil.findControl(name)
        if not ptr:
            return

        ctrl_widget = wrapInstance(int(ptr), QtWidgets.QWidget)
        window      = ctrl_widget.window()
        pos         = window.pos()
        size        = window.size()

        cmds.optionVar(iv=(cls._opt("x"),      pos.x()))
        cmds.optionVar(iv=(cls._opt("y"),      pos.y()))
        cmds.optionVar(iv=(cls._opt("width"),  size.width()))
        cmds.optionVar(iv=(cls._opt("height"), size.height()))

        if not is_floating:
            area = cls._infer_dock_area(window)
            cmds.optionVar(sv=(cls._opt("dockArea"), area))

    @classmethod
    def _infer_dock_area(cls, tool_window):
        """
        Estimate dock area (left / right / bottom) by comparing the tool's
        screen position to Maya's main window. Used when saving docked state.

        Note: Maya doesn't expose the exact dock tab group, so this is a
        best-effort heuristic. The area (left/right/bottom) will be restored
        but not the exact tab position within that area.
        """
        main_geo = _maya_main_window().geometry()
        pos      = tool_window.pos()

        # Below 75% of Maya's height → bottom dock
        if pos.y() > main_geo.y() + main_geo.height() * 0.75:
            return "bottom"
        # Left of Maya's center → left dock
        if pos.x() < main_geo.x() + main_geo.width() / 2:
            return "left"
        return "right"

    # ── Creation ─────────────────────────────────────────────────────────────

    @classmethod
    def _create(cls):
        """Build the workspaceControl and populate it with a widget instance."""
        name  = cls.TOOL_NAME
        state = cls._load_state()

        if state:
            floating  = state["floating"]
            width     = state["width"]
            height    = state["height"]
            restore_x = state["x"]
            restore_y = state["y"]
            dock_area = state["dock_area"]
        else:
            # First launch defaults
            floating  = True
            width     = cls.DEFAULT_WIDTH
            height    = cls.DEFAULT_HEIGHT
            restore_x = None   # None triggers center-on-Maya below
            restore_y = None
            dock_area = "right"

        kwargs = dict(
            label        = cls.TOOL_TITLE,
            uiScript     = cls._ui_script(),
            closeCommand = cls._close_command(),
            retain       = False,   # Destroy on close (state is saved separately)
            floating     = floating,
            width        = width,
            height       = height,
        )

        if not floating:
            # Restore the dock area side; False = don't tab with existing panels
            kwargs["dockToMainWindow"] = (dock_area, False)

        cmds.workspaceControl(name, **kwargs)
        cls._populate_control(name)

        # Position is applied after a Qt event loop tick so the window
        # has fully laid itself out and its final size is known.
        if floating:
            if restore_x is not None:
                QtCore.QTimer.singleShot(
                    0,
                    lambda x=restore_x, y=restore_y: cls._apply_position(x, y)
                )
            else:
                QtCore.QTimer.singleShot(0, cls._center_on_maya)

    @classmethod
    def _populate_control(cls, name):
        """
        Create a widget instance and parent it into the workspaceControl's
        Qt container. Called both on first open and on startup restore.
        """
        ptr = omui.MQtUtil.findControl(name)
        if not ptr:
            om.MGlobal.displayError(
                f"[{cls.TOOL_NAME}] Could not find workspaceControl Qt widget. "
                f"The panel may not have finished initializing."
            )
            return

        parent = wrapInstance(int(ptr), QtWidgets.QWidget)
        widget = cls(parent=parent)

        # Maya's workspaceControl container may already have an internal
        # layout.  Reuse it when present; only create a new one if needed.
        layout = parent.layout()
        if layout is None:
            layout = QtWidgets.QVBoxLayout(parent)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(widget)
        widget.show()

    # ── Position helpers ─────────────────────────────────────────────────────

    @classmethod
    def _apply_position(cls, x, y):
        """Move the floating window to previously saved screen coordinates."""
        name = cls.TOOL_NAME
        if not cmds.workspaceControl(name, exists=True):
            return
        ptr = omui.MQtUtil.findControl(name)
        if not ptr:
            return
        wrapInstance(int(ptr), QtWidgets.QWidget).window().move(x, y)

    @classmethod
    def _center_on_maya(cls):
        """
        Center the floating window over Maya's main window.
        Called on first-ever launch (no saved state).
        """
        name = cls.TOOL_NAME
        if not cmds.workspaceControl(name, exists=True):
            return
        ptr = omui.MQtUtil.findControl(name)
        if not ptr:
            return

        main_geo = _maya_main_window().frameGeometry()
        tool_win = wrapInstance(int(ptr), QtWidgets.QWidget).window()
        tool_geo = tool_win.frameGeometry()

        tool_geo.moveCenter(main_geo.center())
        tool_win.move(tool_geo.topLeft())
